# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate chemometrics-dev
#
name: chemometrics-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - cython
  - matplotlib
  - scipy
  - numpy
  - scikit-learn
  - jupyterlab
  - pandas
  - nbsphinx
  - pandoc
